// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGfbWN_9D6Uv1cI4_f0xUlI5tk3-A14I',
    appId: '1:102787556164:web:d229329414026462b4ed11',
    messagingSenderId: '102787556164',
    projectId: 'mynotes-mulinge',
    authDomain: 'mynotes-mulinge.firebaseapp.com',
    storageBucket: 'mynotes-mulinge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyNqLyKjEYIK8ZOat0zUIv0aBkZ2w3MQ',
    appId: '1:102787556164:android:7d3f06f48ec80595b4ed11',
    messagingSenderId: '102787556164',
    projectId: 'mynotes-mulinge',
    storageBucket: 'mynotes-mulinge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOjynCtdr3E4NM2Eu-I_QGPhAWorFeAU',
    appId: '1:102787556164:ios:602ffd2906f36ef2b4ed11',
    messagingSenderId: '102787556164',
    projectId: 'mynotes-mulinge',
    storageBucket: 'mynotes-mulinge.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOjynCtdr3E4NM2Eu-I_QGPhAWorFeAU',
    appId: '1:102787556164:ios:602ffd2906f36ef2b4ed11',
    messagingSenderId: '102787556164',
    projectId: 'mynotes-mulinge',
    storageBucket: 'mynotes-mulinge.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPGfbWN_9D6Uv1cI4_f0xUlI5tk3-A14I',
    appId: '1:102787556164:web:26f3b418f359c56ab4ed11',
    messagingSenderId: '102787556164',
    projectId: 'mynotes-mulinge',
    authDomain: 'mynotes-mulinge.firebaseapp.com',
    storageBucket: 'mynotes-mulinge.firebasestorage.app',
  );
}
